--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-11-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BNO
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA"."SEQ_BNO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 17 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOOKING_NO
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA"."SEQ_BOOKING_NO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_MEMBER_NO
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA"."SEQ_MEMBER_NO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 13 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ORDER_NO
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA"."SEQ_ORDER_NO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 56 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCT_NO
--------------------------------------------------------

   CREATE SEQUENCE  "JAVA"."SEQ_PRODUCT_NO"  MINVALUE 1 MAXVALUE 9999 INCREMENT BY 1 START WITH 7 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table BOARDS
--------------------------------------------------------

  CREATE TABLE "JAVA"."BOARDS" 
   (	"BNO" NUMBER, 
	"BTITLE" VARCHAR2(100 BYTE), 
	"BCONTENT" VARCHAR2(1000 BYTE), 
	"BWRITER" VARCHAR2(50 BYTE), 
	"BDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "JAVA"."BOOK" 
   (	"TITLE" VARCHAR2(50 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER, 
	"BNUM" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "JAVA"."EMPLOYEE" 
   (	"EMPLOYEE_NO" VARCHAR2(30 BYTE), 
	"EMPLOYEE_NAME" VARCHAR2(30 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"HIRE_DATE" DATE, 
	"SALARY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "JAVA"."MEMBER" 
   (	"MEMBER_NO" NUMBER, 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"BIRTH" DATE, 
	"PHONE" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"GRADE" VARCHAR2(10 BYTE) DEFAULT 'WHITE', 
	"SIGNUP_SOURCE" VARCHAR2(100 BYTE), 
	"AUTH" VARCHAR2(10 BYTE) DEFAULT 'USER', 
	"SIGNUP_DATE" DATE DEFAULT sysdate, 
	"ORDER_NO" NUMBER, 
	"TOTAL_PAYMENT_AMOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDER_DETAILS
--------------------------------------------------------

  CREATE TABLE "JAVA"."ORDER_DETAILS" 
   (	"ORDER_NO" NUMBER, 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"PRODUCT_NO" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER, 
	"IS_DELIVERY" VARCHAR2(10 BYTE), 
	"DEL_PICK_TIME" DATE, 
	"ORDER_TIME" DATE DEFAULT TO_DATE(SYSDATE, 'YYYY-MM-DD HH24:MI:SS'), 
	"MEMBER_ID" VARCHAR2(100 BYTE), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"ORDER_PRICE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "JAVA"."PRODUCT" 
   (	"PRODUCT_NO" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER, 
	"REMAIN_QUANTITY" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TBL_MEMBER
--------------------------------------------------------

  CREATE TABLE "JAVA"."TBL_MEMBER" 
   (	"MEMBER_ID" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE), 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"RESPONSIBILITY" VARCHAR2(10 BYTE) DEFAULT 'User', 
	"CREATION_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JAVA.BOARDS
SET DEFINE OFF;
Insert into JAVA.BOARDS (BNO,BTITLE,BCONTENT,BWRITER,BDATE) values (10,'updated title10','updated bcontent10','writer5',to_date('2024-10-04 11:04:50','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.BOARDS (BNO,BTITLE,BCONTENT,BWRITER,BDATE) values (7,'title4','content4','writer4',to_date('2024-10-04 10:56:13','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.BOARDS (BNO,BTITLE,BCONTENT,BWRITER,BDATE) values (8,'updated btitle8','updated bcontent8','writer5',to_date('2024-10-04 10:56:19','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.BOARDS (BNO,BTITLE,BCONTENT,BWRITER,BDATE) values (9,'updated btitle many','updated bcontent many','writer5',to_date('2024-10-04 11:03:37','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.BOARDS (BNO,BTITLE,BCONTENT,BWRITER,BDATE) values (11,'updated btitle many','updated bcontent many','writer5',to_date('2024-10-04 11:07:55','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.BOARDS (BNO,BTITLE,BCONTENT,BWRITER,BDATE) values (12,'updated btitle many','updated bcontent many','writer5',to_date('2024-10-04 11:09:50','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.BOARDS (BNO,BTITLE,BCONTENT,BWRITER,BDATE) values (13,'updated btitle many','updated bcontent many','writer5',to_date('2024-10-04 11:10:36','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.BOARDS (BNO,BTITLE,BCONTENT,BWRITER,BDATE) values (14,'title5','content5','writer5',to_date('2024-10-04 12:03:20','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.BOARDS (BNO,BTITLE,BCONTENT,BWRITER,BDATE) values (16,'title5','content5','writer5',to_date('2024-10-04 14:14:19','YYYY-MM-DD HH24:MI:SS'));
REM INSERTING into JAVA.BOOK
SET DEFINE OFF;
Insert into JAVA.BOOK (TITLE,WRITER,PRICE,BNUM) values ('jdbc','kim',30000,'333-333');
Insert into JAVA.BOOK (TITLE,WRITER,PRICE,BNUM) values ('java','dayoung',10000,'111-111');
Insert into JAVA.BOOK (TITLE,WRITER,PRICE,BNUM) values ('html','da',20000,'222-222');
REM INSERTING into JAVA.EMPLOYEE
SET DEFINE OFF;
Insert into JAVA.EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,PHONE,HIRE_DATE,SALARY) values ('444-444','gil','010-7777-7777',to_date('2024-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'),100);
Insert into JAVA.EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,PHONE,HIRE_DATE,SALARY) values ('222-222','dayoung','010-2222-2222',to_date('2022-09-09 00:00:00','YYYY-MM-DD HH24:MI:SS'),500);
Insert into JAVA.EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,PHONE,HIRE_DATE,SALARY) values ('111-111','kim','010-0000-0000',to_date('2003-05-03 00:00:00','YYYY-MM-DD HH24:MI:SS'),150);
Insert into JAVA.EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,PHONE,HIRE_DATE,SALARY) values ('333-333','hong','010-3333-3333',to_date('2021-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'),400);
Insert into JAVA.EMPLOYEE (EMPLOYEE_NO,EMPLOYEE_NAME,PHONE,HIRE_DATE,SALARY) values ('777-777','r','3432',to_date('2000-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS'),3);
REM INSERTING into JAVA.MEMBER
SET DEFINE OFF;
Insert into JAVA.MEMBER (MEMBER_NO,MEMBER_NAME,BIRTH,PHONE,ID,PASSWORD,EMAIL,GRADE,SIGNUP_SOURCE,AUTH,SIGNUP_DATE,ORDER_NO,TOTAL_PAYMENT_AMOUNT) values (11,'young',to_date('1990-09-09 00:00:00','YYYY-MM-DD HH24:MI:SS'),'345-3455-3455','young','test1234','aaa@aaa.com','GOLD','search','USER',to_date('2024-10-11 12:33:35','YYYY-MM-DD HH24:MI:SS'),55,14490);
Insert into JAVA.MEMBER (MEMBER_NO,MEMBER_NAME,BIRTH,PHONE,ID,PASSWORD,EMAIL,GRADE,SIGNUP_SOURCE,AUTH,SIGNUP_DATE,ORDER_NO,TOTAL_PAYMENT_AMOUNT) values (3,'dayoung',to_date('1993-03-04 00:00:00','YYYY-MM-DD HH24:MI:SS'),'010-0000-0000','da1234','test1234','ekdud3460@naver.com','WHITE',null,'ADMIN',to_date('2024-10-08 12:27:30','YYYY-MM-DD HH24:MI:SS'),null,null);
REM INSERTING into JAVA.ORDER_DETAILS
SET DEFINE OFF;
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (5,'sdf','dsd','1',1,'true',null,to_date('2024-10-08 17:29:59','YYYY-MM-DD HH24:MI:SS'),null,null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (6,'sdf','dsd','1',1,'true',null,to_date('2024-10-08 17:38:46','YYYY-MM-DD HH24:MI:SS'),null,null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (7,'sdf','dsd','1',1,'true',null,to_date('2024-10-08 17:39:18','YYYY-MM-DD HH24:MI:SS'),null,null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (8,'sdf','dsd','1',1,'true',null,to_date('2024-10-08 17:40:16','YYYY-MM-DD HH24:MI:SS'),null,null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (9,'sdf','dsd','1',1,'true',null,to_date('2024-10-10 09:28:23','YYYY-MM-DD HH24:MI:SS'),null,null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (10,'sdf','dsd','1',1,'true',null,to_date('2024-10-10 09:29:15','YYYY-MM-DD HH24:MI:SS'),null,null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (11,'sdf','dsd','1',1,'true',null,to_date('2024-10-10 09:30:13','YYYY-MM-DD HH24:MI:SS'),null,null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (12,'sdf','dsd','1',1,'true',null,to_date('2024-10-10 09:32:33','YYYY-MM-DD HH24:MI:SS'),null,null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (13,'sdf','dsd','1',1,'true',null,to_date('2024-10-10 09:47:49','YYYY-MM-DD HH24:MI:SS'),'dd',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (14,'kim','2343234','1',10,'true',null,to_date('2024-10-10 14:42:38','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (15,'kim','2343234','3',1,'true',null,to_date('2024-10-10 15:07:03','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (16,'kim','2343234','3',1,'true',null,to_date('2024-10-10 15:07:51','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (17,'kim','2343234','3',1,'true',null,to_date('2024-10-10 15:14:12','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (18,'kim','2343234','3',1,'true',null,to_date('2024-10-10 15:43:22','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (19,'kim','2343234','3',1,'true',null,to_date('2024-10-10 15:45:29','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (20,'kim','2343234','3',1,'true',null,to_date('2024-10-10 15:46:46','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (21,'kim','2343234','3',1,'true',null,to_date('2024-10-10 15:47:39','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (22,'kim','2343234','3',1,'true',null,to_date('2024-10-10 15:48:50','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (23,'kim','2343234','3',1,'true',null,to_date('2024-10-10 15:49:06','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (24,'kim','2343234','3',1,'true',null,to_date('2024-10-10 16:09:21','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (25,'kim','2343234','3',1,'true',null,to_date('2024-10-10 16:11:14','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (26,'kim','2343234','3',1,'true',null,to_date('2024-10-10 16:21:47','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (27,'kim','2343234','3',1,'true',null,to_date('2024-10-10 16:58:36','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (28,'kim','2343234','4',1,'true',null,to_date('2024-10-10 17:01:29','YYYY-MM-DD HH24:MI:SS'),'kim',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (29,'hong','020-2344-2344','4',1,'true',null,to_date('2024-10-10 17:03:52','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (30,'hong','020-2344-2344','4',1,'true',null,to_date('2024-10-10 17:25:25','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (31,'hong','020-2344-2344','4',1,'true',null,to_date('2024-10-10 17:27:03','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (32,'hong','020-2344-2344','4',1,'true',null,to_date('2024-10-10 17:30:16','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (33,'hong','020-2344-2344','4',1,'true',null,to_date('2024-10-10 17:32:23','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (34,'hong','020-2344-2344','4',1,'true',null,to_date('2024-10-10 17:33:05','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (35,'hong','020-2344-2344','4',30,'true',null,to_date('2024-10-10 17:43:51','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (36,'hong','020-2344-2344','4',50,'true',null,to_date('2024-10-10 17:45:41','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (37,'hong','020-2344-2344','4',1,'true',null,to_date('2024-10-10 17:49:58','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (38,'hong','020-2344-2344','4',1,'true',null,to_date('2024-10-10 17:51:33','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (39,'hong','020-2344-2344','1',3,'false',null,to_date('2024-10-11 10:25:55','YYYY-MM-DD HH24:MI:SS'),'hong',null,null);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (40,'hong','020-2344-2344','1',1,'true',null,to_date('2024-10-11 10:53:37','YYYY-MM-DD HH24:MI:SS'),'hong','pizza',2000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (41,'hong','020-2344-2344','5',2,'true',null,to_date('0024-10-11 00:00:00','YYYY-MM-DD HH24:MI:SS'),'hong','beef',8000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (42,'hong','020-2344-2344','4',4,'true',null,to_date('0024-10-11 00:00:00','YYYY-MM-DD HH24:MI:SS'),'hong','candy',400);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (43,'hong','020-2344-2344','1',1,'true',null,to_date('0024-10-11 00:00:00','YYYY-MM-DD HH24:MI:SS'),'hong','pizza',2000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (44,'hong','020-2344-2344','5',1,'true',null,to_date('0024-10-11 00:00:00','YYYY-MM-DD HH24:MI:SS'),'hong','beef',4000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (45,'hong','020-2344-2344','5',1,'true',null,to_date('0024-10-11 00:00:00','YYYY-MM-DD HH24:MI:SS'),'hong','beef',4000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (46,'hong','020-2344-2344','1',1,'true',null,to_date('2024-10-11 12:04:01','YYYY-MM-DD HH24:MI:SS'),'hong','pizza',2000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (47,'hong','020-2344-2344','5',1,'false',to_date('2024-10-11 13:26:22','YYYY-MM-DD HH24:MI:SS'),to_date('2024-10-11 12:26:22','YYYY-MM-DD HH24:MI:SS'),'hong','beef',4000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (48,'hong','020-2344-2344','1',3,'true',to_date('2024-10-11 13:52:14','YYYY-MM-DD HH24:MI:SS'),to_date('2024-10-11 12:52:14','YYYY-MM-DD HH24:MI:SS'),'hong','pizza',6000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (49,'young','010-2344-2344','4',6,'false',to_date('2024-10-11 13:55:26','YYYY-MM-DD HH24:MI:SS'),to_date('2024-10-11 12:55:26','YYYY-MM-DD HH24:MI:SS'),'young','candy',600);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (50,'young','010-2344-2344','5',3,'false',to_date('2024-10-11 15:13:21','YYYY-MM-DD HH24:MI:SS'),to_date('2024-10-11 14:13:21','YYYY-MM-DD HH24:MI:SS'),'young','beef',12000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (51,'young','010-2344-2344','4',1,'false',to_date('2024-10-11 17:52:08','YYYY-MM-DD HH24:MI:SS'),to_date('2024-10-11 16:52:08','YYYY-MM-DD HH24:MI:SS'),'young','candy',100);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (52,'young','345-3455-3455','1',2,'false',to_date('2024-10-11 18:25:40','YYYY-MM-DD HH24:MI:SS'),to_date('2024-10-11 17:25:40','YYYY-MM-DD HH24:MI:SS'),'young','chocolate',1000);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (53,'young','345-3455-3455','1',1,'true',to_date('2024-10-11 18:41:48','YYYY-MM-DD HH24:MI:SS'),to_date('2024-10-11 17:41:48','YYYY-MM-DD HH24:MI:SS'),'young','chocolate',500);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (54,'young','345-3455-3455','1',1,'true',to_date('2024-10-11 18:43:48','YYYY-MM-DD HH24:MI:SS'),to_date('2024-10-11 17:43:48','YYYY-MM-DD HH24:MI:SS'),'young','chocolate',500);
Insert into JAVA.ORDER_DETAILS (ORDER_NO,MEMBER_NAME,PHONE,PRODUCT_NO,QUANTITY,IS_DELIVERY,DEL_PICK_TIME,ORDER_TIME,MEMBER_ID,PRODUCT_NAME,ORDER_PRICE) values (55,'young','345-3455-3455','1',1,'true',to_date('2024-10-11 18:52:52','YYYY-MM-DD HH24:MI:SS'),to_date('2024-10-11 17:52:52','YYYY-MM-DD HH24:MI:SS'),'young','chocolate',500);
REM INSERTING into JAVA.PRODUCT
SET DEFINE OFF;
Insert into JAVA.PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRICE,REMAIN_QUANTITY) values (1,'chocolate',500,35);
Insert into JAVA.PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRICE,REMAIN_QUANTITY) values (6,'water',900,10);
Insert into JAVA.PRODUCT (PRODUCT_NO,PRODUCT_NAME,PRICE,REMAIN_QUANTITY) values (5,'beef',4000,2);
REM INSERTING into JAVA.TBL_MEMBER
SET DEFINE OFF;
Insert into JAVA.TBL_MEMBER (MEMBER_ID,PASSWORD,MEMBER_NAME,PHONE,RESPONSIBILITY,CREATION_DATE) values ('user01','123456789','홍길동','010-1111-2222','User',to_date('2024-10-07 09:35:00','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.TBL_MEMBER (MEMBER_ID,PASSWORD,MEMBER_NAME,PHONE,RESPONSIBILITY,CREATION_DATE) values ('guest','5555555','김손님',null,'User',to_date('2024-10-07 09:35:03','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.TBL_MEMBER (MEMBER_ID,PASSWORD,MEMBER_NAME,PHONE,RESPONSIBILITY,CREATION_DATE) values ('admin','9999','관리자',null,'Admin',to_date('2024-10-07 12:51:53','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.TBL_MEMBER (MEMBER_ID,PASSWORD,MEMBER_NAME,PHONE,RESPONSIBILITY,CREATION_DATE) values ('user02','111','dayoung','010-2222-2222','User',to_date('2024-10-07 15:49:24','YYYY-MM-DD HH24:MI:SS'));
Insert into JAVA.TBL_MEMBER (MEMBER_ID,PASSWORD,MEMBER_NAME,PHONE,RESPONSIBILITY,CREATION_DATE) values ('user03','222','kim','010-3333-3333','Admin',to_date('2024-10-07 15:51:52','YYYY-MM-DD HH24:MI:SS'));
--------------------------------------------------------
--  DDL for Trigger TRG_MEMBER_NO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JAVA"."TRG_MEMBER_NO" 
BEFORE INSERT ON member
FOR EACH ROW
 WHEN (NEW.member_no IS NULL) BEGIN
  :NEW.member_no := seq_member_no.NEXTVAL;
END;

/
ALTER TRIGGER "JAVA"."TRG_MEMBER_NO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_ORDER_NO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JAVA"."TRG_ORDER_NO" 
BEFORE INSERT ON order_details
FOR EACH ROW
 WHEN (NEW.order_no IS NULL) BEGIN
  :NEW.order_no := seq_order_no.NEXTVAL;
END;
/

ALTER TRIGGER "JAVA"."TRG_ORDER_NO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRG_PRODUCT_NO
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JAVA"."TRG_PRODUCT_NO" 
    BEFORE INSERT ON product
    FOR EACH ROW
     WHEN (NEW.product_no IS NULL) BEGIN
    :NEW.product_no := seq_product_no.NEXTVAL;
END;
/

ALTER TRIGGER "JAVA"."TRG_PRODUCT_NO" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPDATE_DEL_PICK_TIME
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JAVA"."UPDATE_DEL_PICK_TIME" 
    BEFORE INSERT ON ORDER_DETAILS
    FOR EACH ROW
    BEGIN
    :NEW.DEL_PICK_TIME := :NEW.ORDER_TIME + INTERVAL '1' HOUR;
END;
/
ALTER TRIGGER "JAVA"."UPDATE_DEL_PICK_TIME" ENABLE;
--------------------------------------------------------
--  DDL for Trigger UPDATE_MEMBER_GRADE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "JAVA"."UPDATE_MEMBER_GRADE" 
    BEFORE UPDATE OF total_payment_amount ON member
    FOR EACH ROW
    IF :NEW.total_payment_amount > 10000 THEN        :NEW.grade := 'GOLD';    ELSE IF :NEW.total_payment_amount > 5000 THEN        :NEW.grade := 'SILVER';    ELSE        :NEW.grade := 'WHITE';    END IF;END;
/
ALTER TRIGGER "JAVA"."UPDATE_MEMBER_GRADE" ENABLE;
commit;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "JAVA"."BOOK" MODIFY ("BNUM" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."BOOK" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."BOOK" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."BOOK" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "JAVA"."EMPLOYEE" ADD PRIMARY KEY ("EMPLOYEE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."EMPLOYEE" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."EMPLOYEE" MODIFY ("HIRE_DATE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."EMPLOYEE" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."EMPLOYEE" MODIFY ("EMPLOYEE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "JAVA"."PRODUCT" ADD PRIMARY KEY ("PRODUCT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDER_DETAILS
--------------------------------------------------------

  ALTER TABLE "JAVA"."ORDER_DETAILS" ADD PRIMARY KEY ("ORDER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."ORDER_DETAILS" MODIFY ("IS_DELIVERY" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."ORDER_DETAILS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."ORDER_DETAILS" MODIFY ("PRODUCT_NO" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."ORDER_DETAILS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."ORDER_DETAILS" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARDS
--------------------------------------------------------

  ALTER TABLE "JAVA"."BOARDS" ADD PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."BOARDS" MODIFY ("BWRITER" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."BOARDS" MODIFY ("BCONTENT" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."BOARDS" MODIFY ("BTITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_MEMBER
--------------------------------------------------------

  ALTER TABLE "JAVA"."TBL_MEMBER" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."TBL_MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."TBL_MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "JAVA"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JAVA"."MEMBER" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MEMBER" MODIFY ("BIRTH" NOT NULL ENABLE);
  ALTER TABLE "JAVA"."MEMBER" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
